#! /bin/sh
### BEGIN INIT INFO
# Provides:          asneg
# Required-Start: 
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start OPC UA server.
# Description:       Start OPC UA server.
### END INIT INFO



NAME=OpcUaServer4
DAEMON_PATH=/opt/opcua/bin
DAEMON=$DAEMON_PATH/$NAME
DAEMON_OPT="$DAEMON_PATH/etc/OpcUaStack/OpcUaServer.xml"
PIDFILE=/var/run/$NAME.pid

LOGDIR=$DAEMON_PATH/var/log/OpcUaStack
CFGSRC=$DAEMON_PATH/../cfg/etc


if [ -f /lib/lsb/init-functions ]; then
        . /lib/lsb/init-functions
elif [ -f /etc/init.d/functions ]; then
        . /etc/init.d/functions
else
        log_daemon_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            echo "$@"
        }

        log_end_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            if [ $1 -eq 0 ]; then
                echo "... done"
            else
                echo "... failed"
            fi
        }

        log_action_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            echo "$@"
        }

fi


echo start-stop-daemon --chdir $DAEMON_PATH --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON $DAEMON_OPT
test -f $DAEMON || exit 0

d_start () {
        log_daemon_msg "Starting ASNeG OPC UA Server"
	mkdir -p $LOGDIR
	cp -rf $CFGSRC $DAEMON_PATH
	start-stop-daemon --chdir $DAEMON_PATH --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec $DAEMON $DAEMON_OPT
        log_end_msg $?
}

d_stop() {
        log_daemon_msg "Stopping ASNeG OPC UA Server"
        start-stop-daemon --stop --pidfile $PIDFILE
        rm -rf $PIDFILE
        log_end_msg $?
}

case "$1" in
  start)
    d_start
        ;;
  stop)
    d_stop
        ;;

  reload|force-reload|restart)
    d_stop
    sleep 1
    d_start
        ;;

  force-stop)
    d_stop
    killall -q $NAME || true
    sleep 2
    killall -q -9 $NAME || true
    ;;

  status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;

  *)
        log_action_msg "Usage: service asneg {start|stop|reload|force-reload|restart|status}"
        exit 1
esac

REATE USER 'opcuaUser'@'localhost' IDENTIFIED BY 'opcua_Password'; GRANT ALL PRIVILEGES ON * . * TO 'opcuaUser'@'localhost'; FLUSH PRIVILEGES; 
