#! /bin/sh

### BEGIN INIT INFO
# Provides:             leshan
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    LWM2M Server
### END INIT INFO

set -e

# /etc/init.d/leshan: start and stop the Leshan LWM2M Server
WEBPORT=5555
COAPPORT=56583
COAPSPORT=56584

NAME=leshan-server-demo
DAEMON_PATH=/opt/leshan
DAEMON=$DAEMON_PATH/$NAME.jar
DAEMON_OPT="-wp $WEBPORT -lp $COAPPORT -slp $COAPSPORT"
PIDFILE=/var/run/$NAME.pid

#echo "start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec /usr/bin/java -- -jar $DAEMON $DAEMON_OPT"
#start-stop-daemon --start --quiet --make-pidfile --pidfile /var/run/leshan-server-dem --background --exec /usr/bin/java -- -jar /root/leshan-server-demo.jar -wp 5555

umask 022

# Get IPV6 address
IF=br0
IPV6=$(ip addr show dev $IF | sed -e 's/^.*inet6 \([^ ]*\)\/.*$/\1/;t;d' | head -n1)


# Port configurations
#export COAPIFACE=$IPV6:5683 
#export COAPSIFACE=$IPV6:5684 
# Start the standalone server
#java -jar leshan-standalone/target/leshan-standalone-*-SNAPSHOT-jar-with-dependencies.jar



if [ -f /lib/lsb/init-functions ]; then
        . /lib/lsb/init-functions
elif [ -f /etc/init.d/functions ]; then
        . /etc/init.d/functions
else
        log_daemon_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            echo "$@"
        }

        log_end_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            if [ $1 -eq 0 ]; then
                echo "... done"
            else
                echo "... failed"
            fi
        }

        log_action_msg () {
            if [ -z "${1:-}" ]; then
                return 1
            fi
            echo "$@"
        }

fi

test -f $DAEMON || exit 0

d_start () {
        log_daemon_msg "Starting Leshan LWM2M Server"
        start-stop-daemon --start --quiet --make-pidfile --pidfile $PIDFILE --background --exec /usr/bin/java -- -jar $DAEMON $DAEMON_OPT
        log_end_msg $?
}

d_stop() {
        log_daemon_msg "Stopping Leshan LWM2M Server"
        start-stop-daemon --stop --pidfile $PIDFILE
        rm -rf $PIDFILE
        log_end_msg $?
}

case "$1" in
  start)
    d_start
        ;;
  stop)
    d_stop
        ;;

  reload|force-reload|restart)
    d_stop
    sleep 1
    d_start
        ;;

  force-stop)
    d_stop
    killall -q $NAME || true
    sleep 2
    killall -q -9 $NAME || true
    ;;

  status)
        status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
        ;;

  *)
        log_action_msg "Usage: /etc/init.d/leshan {start|stop|reload|force-reload|restart|status}"
        exit 1
esac

exit 0
