#! /bin/sh
### BEGIN INIT INFO
# Provides:          asneg-wd
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start OPC UA server watchdog.
# Description:       Start OPC UA server watchdog.
### END INIT INFO

#set -e

MYSERVICE_PID=`pidof OpcUaServer3`
MYSERVICE_NAME=asneg

check_myservice() {
        if [ -z $MYSERVICE_PID ];then
                service $MYSERVICE_NAME restart
        fi
}

check_myservice

usage() {
    echo "$MYSERVICE_NAME {start|stop|status}"
    exit 0
}

case $1 in
    start ) if [ -z $MYSERVICE_PID ];then
        service $MYSERVICE_NAME restart
        else
            echo "$MYSERVICE_NAME is already running"
        fi
        ;;
    stop ) if [ -n $MYSERVICE_PID ];then
        service $MYSERVICE_NAME stop
        else
            echo "$MYSERVICE_NAME is already stopped"
        fi
        ;;
    status) if [ -z $MYSERVICE_PID ];then
            echo "$MYSERVICE_NAME is not running"
        else
            echo "$MYSERVICE_NAME is running"
        fi
        ;;
    *) usage
        ;;
esac
exit 0
